/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuarterlyRouteImport } from './routes/quarterly'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiDeleteAccountRouteImport } from './routes/api/delete-account'
import { Route as ApiPlaidSyncRouteImport } from './routes/api/plaid/sync'
import { Route as ApiPlaidInstitutionsRouteImport } from './routes/api/plaid/institutions'
import { Route as ApiPlaidExchangeTokenRouteImport } from './routes/api/plaid/exchange-token'
import { Route as ApiPlaidCreateLinkTokenRouteImport } from './routes/api/plaid/create-link-token'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarterlyRoute = QuarterlyRouteImport.update({
  id: '/quarterly',
  path: '/quarterly',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteAccountRoute = ApiDeleteAccountRouteImport.update({
  id: '/api/delete-account',
  path: '/api/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaidSyncRoute = ApiPlaidSyncRouteImport.update({
  id: '/api/plaid/sync',
  path: '/api/plaid/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaidInstitutionsRoute = ApiPlaidInstitutionsRouteImport.update({
  id: '/api/plaid/institutions',
  path: '/api/plaid/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaidExchangeTokenRoute = ApiPlaidExchangeTokenRouteImport.update({
  id: '/api/plaid/exchange-token',
  path: '/api/plaid/exchange-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaidCreateLinkTokenRoute = ApiPlaidCreateLinkTokenRouteImport.update({
  id: '/api/plaid/create-link-token',
  path: '/api/plaid/create-link-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/quarterly': typeof QuarterlyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/plaid/create-link-token': typeof ApiPlaidCreateLinkTokenRoute
  '/api/plaid/exchange-token': typeof ApiPlaidExchangeTokenRoute
  '/api/plaid/institutions': typeof ApiPlaidInstitutionsRoute
  '/api/plaid/sync': typeof ApiPlaidSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/quarterly': typeof QuarterlyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/plaid/create-link-token': typeof ApiPlaidCreateLinkTokenRoute
  '/api/plaid/exchange-token': typeof ApiPlaidExchangeTokenRoute
  '/api/plaid/institutions': typeof ApiPlaidInstitutionsRoute
  '/api/plaid/sync': typeof ApiPlaidSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/quarterly': typeof QuarterlyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/terms': typeof TermsRoute
  '/transactions': typeof TransactionsRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/plaid/create-link-token': typeof ApiPlaidCreateLinkTokenRoute
  '/api/plaid/exchange-token': typeof ApiPlaidExchangeTokenRoute
  '/api/plaid/institutions': typeof ApiPlaidInstitutionsRoute
  '/api/plaid/sync': typeof ApiPlaidSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/export'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/quarterly'
    | '/settings'
    | '/signup'
    | '/subscriptions'
    | '/terms'
    | '/transactions'
    | '/api/delete-account'
    | '/api/stripe-webhook'
    | '/api/plaid/create-link-token'
    | '/api/plaid/exchange-token'
    | '/api/plaid/institutions'
    | '/api/plaid/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/export'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/quarterly'
    | '/settings'
    | '/signup'
    | '/subscriptions'
    | '/terms'
    | '/transactions'
    | '/api/delete-account'
    | '/api/stripe-webhook'
    | '/api/plaid/create-link-token'
    | '/api/plaid/exchange-token'
    | '/api/plaid/institutions'
    | '/api/plaid/sync'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/dashboard'
    | '/export'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/quarterly'
    | '/settings'
    | '/signup'
    | '/subscriptions'
    | '/terms'
    | '/transactions'
    | '/api/delete-account'
    | '/api/stripe-webhook'
    | '/api/plaid/create-link-token'
    | '/api/plaid/exchange-token'
    | '/api/plaid/institutions'
    | '/api/plaid/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRoute
  ExportRoute: typeof ExportRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  QuarterlyRoute: typeof QuarterlyRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TermsRoute: typeof TermsRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiDeleteAccountRoute: typeof ApiDeleteAccountRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiPlaidCreateLinkTokenRoute: typeof ApiPlaidCreateLinkTokenRoute
  ApiPlaidExchangeTokenRoute: typeof ApiPlaidExchangeTokenRoute
  ApiPlaidInstitutionsRoute: typeof ApiPlaidInstitutionsRoute
  ApiPlaidSyncRoute: typeof ApiPlaidSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarterly': {
      id: '/quarterly'
      path: '/quarterly'
      fullPath: '/quarterly'
      preLoaderRoute: typeof QuarterlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-account': {
      id: '/api/delete-account'
      path: '/api/delete-account'
      fullPath: '/api/delete-account'
      preLoaderRoute: typeof ApiDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plaid/sync': {
      id: '/api/plaid/sync'
      path: '/api/plaid/sync'
      fullPath: '/api/plaid/sync'
      preLoaderRoute: typeof ApiPlaidSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plaid/institutions': {
      id: '/api/plaid/institutions'
      path: '/api/plaid/institutions'
      fullPath: '/api/plaid/institutions'
      preLoaderRoute: typeof ApiPlaidInstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plaid/exchange-token': {
      id: '/api/plaid/exchange-token'
      path: '/api/plaid/exchange-token'
      fullPath: '/api/plaid/exchange-token'
      preLoaderRoute: typeof ApiPlaidExchangeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plaid/create-link-token': {
      id: '/api/plaid/create-link-token'
      path: '/api/plaid/create-link-token'
      fullPath: '/api/plaid/create-link-token'
      preLoaderRoute: typeof ApiPlaidCreateLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRoute,
  ExportRoute: ExportRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  QuarterlyRoute: QuarterlyRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TermsRoute: TermsRoute,
  TransactionsRoute: TransactionsRoute,
  ApiDeleteAccountRoute: ApiDeleteAccountRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiPlaidCreateLinkTokenRoute: ApiPlaidCreateLinkTokenRoute,
  ApiPlaidExchangeTokenRoute: ApiPlaidExchangeTokenRoute,
  ApiPlaidInstitutionsRoute: ApiPlaidInstitutionsRoute,
  ApiPlaidSyncRoute: ApiPlaidSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
